#! /bin/bash
set -o nounset

rootdir="/home/dbaker/bin/kb-utility" # TODO fix this

# States
CHARGING=1
DISCHARGING=2

LEVEL_NORMAL=3
LEVEL_LOW=4
LEVEL_CRITICAL=5

ON=6
OFF=7


# Battery danger levels
critical_level=10
low_level=20

state_charging=$CHARGING
state_level=$LEVEL_NORMAL
state_on=$ON

isDischarging () {
    batterylevel=$(acpi -V | awk '/Discharging/ { print ($4 + 0) }')
    acpi -V | grep -q "Discharging"

    # Grep command will exit with zero if it finds the string, hence this unintuitive logic
    discharging=$?
    return $discharging
}

isOn () {
    batterylevel=$(acpi -V | awk '/Discharging/ { print ($4 + 0) }')
    cat /etc/modprobe.d/clevo-xsm-wmi.conf | grep -q "kb_off=0"

    # Grep command will exit with zero if it finds the string, hence this unintuitive logic
    on=$?
    return $on
}


if isDischarging; then
    state_charging=$DISCHARGING
else
    state_charging=$CHARGING
fi

if [[ $batterylevel -le $critical_level ]]; then
    state_level=$LEVEL_CRITICAL
elif [[ $batterylevel -le $low_level ]]; then
    state_level=$LEVEL_LOW
else
    state_level=$LEVEL_NORMAL
fi

if isOn; then
    state_on=$ON
else
    state_on=$OFF
fi

# Only turn on the keyboard if we already have it set to on
if [[ state_on -eq $ON ]]; then

    if [[ state_charging -eq $DISCHARGING ]]; then

        if [[ state_level -eq $LEVEL_LOW ]]; then
            # Make keyboard low battery-colored
            cat "$rootdir/kb-on.txt" "$rootdir/lowbat.txt" | sudo tee /etc/modprobe.d/clevo-xsm-wmi.conf > /dev/null
            sudo modprobe -r clevo_xsm_wmi
            sudo modprobe clevo_xsm_wmi

        elif [[ state_level -eq $LEVEL_CRITICAL ]]; then
            # Make keyboard critical battery-colored
            cat "$rootdir/kb-on.txt" "$rootdir/criticalbat.txt" | sudo tee /etc/modprobe.d/clevo-xsm-wmi.conf > /dev/null
            sudo modprobe -r clevo_xsm_wmi
            sudo modprobe clevo_xsm_wmi
        fi
    
    fi

    if [[ state_level -eq $LEVEL_NORMAL ]]; then
        # Load saved color state
        cat "$rootdir/state.txt" | sudo tee /etc/modprobe.d/clevo-xsm-wmi.conf > /dev/null
        sudo modprobe -r clevo_xsm_wmi
        sudo modprobe clevo_xsm_wmi
    fi

fi
