#! /bin/bash
set -o nounset

rootdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
settingsdir="$rootdir/settings"
default="$settingsdir/default.txt" # default colorscheme

grep -q "color_left=0x000000 color_center=0x000000 color_right=0x000000" /etc/modprobe.d/tuxedo_keyboard.conf
backlight_off=$? # Is the backlight off or on?


showOptions () {
    printf "Usage:\n"
    printf "  kbtoggle    Turn backlight on or off\n"
}



# Create state file if it doesn't exist (will be empty initially)
if [ ! -f "$settingsdir/state.txt" ]; then
    > "$settingsdir/state.txt"
fi

if [ $# -eq 0 ]; then
    printf "Toggling backlight\n\n"

   # Toggle backlight
   if [ $backlight_off -eq 0 ]; then
        echo "> Turning on keyboard backlight..."
        # Concatenate color state with ON code
        # Use a default if no existing state

        if [ ! -s "$settingsdir/state.txt" ]; then
            echo "No existing state, falling back to default."
            cat "$default" | sudo tee /etc/modprobe.d/tuxedo_keyboard.conf > /dev/null
        else
            echo "Using last set colorscheme."
            cat "$settingsdir/state.txt" | sudo tee /etc/modprobe.d/tuxedo_keyboard.conf > /dev/null
        fi

        sudo modprobe -r tuxedo_keyboard
        sudo modprobe tuxedo_keyboard
        printf "\nKeyboard backlight turned on\n"
    else
        echo "> Turning off keyboard backlight..."
        cat "$settingsdir/kb-off.txt" | sudo tee /etc/modprobe.d/tuxedo_keyboard.conf > /dev/null
        sudo modprobe -r tuxedo_keyboard
        sudo modprobe tuxedo_keyboard
        printf "\nKeyboard backlight turned off\n"
    fi
    exit 0
else
    showOptions
    exit 2
fi
