#! /bin/bash
set -o nounset

rootdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
tdir="$rootdir/kb-templates" # template folder

grep -q "kb_off=1" /etc/modprobe.d/clevo-xsm-wmi.conf
backlight_off=$? # Is the backlight off or on?

default="$rootdir/default.txt" # default colorscheme

showOptions () {
    printf "Usage:\n"
    printf "  kbtoggle    Turn backlight on or off\n"
}



# Create state file if it doesn't exist (will be empty initially)
if [ ! -f "$rootdir/state.txt" ]; then
    > state.txt
fi

if [ $# -eq 0 ]; then
    printf "Toggling backlight\n\n"

   # Toggle backlight
   if [ $backlight_off -eq 0 ]; then
        echo "> Turning on keyboard backlight..."
        # Concatenate color state with ON code
        # Use a default if no existing state

        if [ ! -s "$rootdir/state.txt" ]; then
            echo "No existing state, falling back to default."
            cat "$rootdir/kb-on.txt" "$default" | sudo tee /etc/modprobe.d/clevo-xsm-wmi.conf > /dev/null
        else
            echo "Using last set colorscheme."
            cat "$rootdir/kb-on.txt" "$rootdir/state.txt" | sudo tee /etc/modprobe.d/clevo-xsm-wmi.conf > /dev/null
        fi

        sudo modprobe -r clevo_xsm_wmi
        sudo modprobe clevo_xsm_wmi
        printf "\nKeyboard backlight turned on\n"
    else
        echo "> Turning off keyboard backlight..."
        cat "$rootdir/kb-off.txt" | sudo tee /etc/modprobe.d/clevo-xsm-wmi.conf > /dev/null
        sudo modprobe -r clevo_xsm_wmi
        sudo modprobe clevo_xsm_wmi
        printf "\nKeyboard backlight turned off\n"
    fi
    exit 0
else
    showOptions
    exit 2
fi
